name: pangeo
channels:
  - conda-forge
dependencies:
  - nomkl
  - curl=7.61
  - python=3.6
  - xarray=0.11
  - dask=0.20.2
  - distributed=1.24
  - matplotlib=3.0
  - nbserverproxy=0.8
  - jupyter=1.0
  - ipywidgets=7.4
  - graphviz=2.38
  - jupyterlab=0.35
  - nodejs=8.12
  - libgdal=2.3.2
  - boto3=1.9
  - hvplot=0.2
  - requests=2.20
  - pandas=0.23
  - dask-kubernetes=0.6
  - rasterio=1.0.9
  - pip:
#    - wurlitzer==1.0.2
#    - kubernetes==7.0.0
